import animatePlugin from 'tailwindcss-animate';

export default {
	darkMode: ['class'],
	content: ['./index.html', './src/**/*.{ts,tsx,js,jsx}'],
	theme: {
		extend: {
			fontSize: {
				xs: '12px',
				sm: '14px',
			},
			fontFamily: {
				sans: ['var(--font-sans)'],
				geist: ['Geist', 'sans-serif'],
				'fira-code': ['Fira Code', 'monospace'],
			},
			borderRadius: {
				DEFAULT: '6px',
				sm: '6px',
				md: '6px',
				lg: '6px',
				xl: '6px',
				'2xl': '6px',
				'3xl': '6px',
				full: '9999px',
			},
			colors: {
				background: 'hsl(var(--background))',
				foreground: 'hsl(var(--foreground))',
				card: {
					DEFAULT: 'hsl(var(--card))',
					foreground: 'hsl(var(--card-foreground))',
				},
				popover: {
					DEFAULT: 'hsl(var(--popover))',
					foreground: 'hsl(var(--popover-foreground))',
				},
				blue: {
					/*
					 * Re-pointed from the literals '#3293D9' / '#E5F0FF' at the byte-identical brand
					 * tokens. ErrorBoundary uses blue-DEFAULT 26 times (with /5../80 alpha variants);
					 * as literals none of them could theme. Light is unchanged: --fp-brand-blue is
					 * #3293d9 and --fp-brand-blue-light is #e5f0ff, the exact values they replaced.
					 */
					DEFAULT: 'rgb(var(--fp-brand-blue) / <alpha-value>)',
					light: 'rgb(var(--fp-brand-blue-light) / <alpha-value>)',
				},
				primary: {
					DEFAULT: 'hsl(var(--primary))',
					foreground: 'hsl(var(--primary-foreground))',
				},
				secondary: {
					DEFAULT: 'hsl(var(--secondary))',
					foreground: 'hsl(var(--secondary-foreground))',
				},
				muted: {
					DEFAULT: 'hsl(var(--muted))',
					/*
					 * Was the literal '#64748B', which made `text-muted-foreground` (250 uses — the
					 * second most common colour class in the app) unthemable: the `--muted-foreground`
					 * CSS variable was dead, so retuning it for dark did nothing.
					 *
					 * `--fp-content-slate-muted` resolves to slate.500 = #64748b, byte-identical to the
					 * literal it replaces.
					 */
					foreground: 'rgb(var(--fp-content-slate-muted) / <alpha-value>)',
				},
				accent: {
					DEFAULT: 'hsl(var(--accent))',
					foreground: 'hsl(var(--accent-foreground))',
				},
				destructive: {
					DEFAULT: 'hsl(var(--destructive))',
					foreground: 'hsl(var(--destructive-foreground))',
				},
				border: 'hsl(var(--border))',
				input: 'hsl(var(--input))',
				ring: 'hsl(var(--ring))',
				chart: {
					1: 'hsl(var(--chart-1))',
					2: 'hsl(var(--chart-2))',
					3: 'hsl(var(--chart-3))',
					4: 'hsl(var(--chart-4))',
					5: 'hsl(var(--chart-5))',
				},

				/* fp-tokens:begin — generated by scripts/generate-theme-tokens.mjs, do not hand-edit */
				/* ------------------------------------------------------------------
				 * Dark-theme token layer. Light values are byte-identical to the Tailwind
				 * palette colors they replace — see scripts/theme-tokens.mjs and the guard
				 * at scripts/verify-theme-tokens.mjs.
				 * ------------------------------------------------------------------ */

				/* Surfaces — backgrounds. Midnight layers chrome (darkest) under panels (lighter). */
				surface: 'rgb(var(--fp-surface) / <alpha-value>)',
				'surface-subtle': 'rgb(var(--fp-surface-subtle) / <alpha-value>)',
				'surface-muted': 'rgb(var(--fp-surface-muted) / <alpha-value>)',
				'surface-shell': 'rgb(var(--fp-surface-shell) / <alpha-value>)',
				'surface-strong': 'rgb(var(--fp-surface-strong) / <alpha-value>)',
				'surface-heavy': 'rgb(var(--fp-surface-heavy) / <alpha-value>)',
				'surface-faint': 'rgb(var(--fp-surface-faint) / <alpha-value>)',
				'surface-canvas': 'rgb(var(--fp-surface-canvas) / <alpha-value>)',
				'surface-cool': 'rgb(var(--fp-surface-cool) / <alpha-value>)',
				'surface-inverse': 'rgb(var(--fp-surface-inverse) / <alpha-value>)',
				'surface-inverse-zinc': 'rgb(var(--fp-surface-inverse-zinc) / <alpha-value>)',
				'surface-track': 'rgb(var(--fp-surface-track) / <alpha-value>)',
				'surface-scrim': 'rgb(var(--fp-surface-scrim) / <alpha-value>)',

				/* Content — text, icons, fills. The light ramp inverts to the Midnight text ramp. */
				content: 'rgb(var(--fp-content) / <alpha-value>)',
				'content-heading': 'rgb(var(--fp-content-heading) / <alpha-value>)',
				'content-secondary': 'rgb(var(--fp-content-secondary) / <alpha-value>)',
				'content-tertiary': 'rgb(var(--fp-content-tertiary) / <alpha-value>)',
				'content-muted': 'rgb(var(--fp-content-muted) / <alpha-value>)',
				'content-subtle': 'rgb(var(--fp-content-subtle) / <alpha-value>)',
				'content-disabled': 'rgb(var(--fp-content-disabled) / <alpha-value>)',
				'content-inverse': 'rgb(var(--fp-content-inverse) / <alpha-value>)',
				'content-black': 'rgb(var(--fp-content-black) / <alpha-value>)',

				/* Content (zinc ramp) — exists only to keep light byte-identical. Collapsible later. */
				'content-zinc': 'rgb(var(--fp-content-zinc) / <alpha-value>)',
				'content-zinc-bold': 'rgb(var(--fp-content-zinc-bold) / <alpha-value>)',
				'content-zinc-strong': 'rgb(var(--fp-content-zinc-strong) / <alpha-value>)',
				'content-zinc-secondary': 'rgb(var(--fp-content-zinc-secondary) / <alpha-value>)',
				'content-zinc-tertiary': 'rgb(var(--fp-content-zinc-tertiary) / <alpha-value>)',
				'content-zinc-muted': 'rgb(var(--fp-content-zinc-muted) / <alpha-value>)',
				'content-zinc-disabled': 'rgb(var(--fp-content-zinc-disabled) / <alpha-value>)',
				'content-zinc-subtle': 'rgb(var(--fp-content-zinc-subtle) / <alpha-value>)',

				/* Content (slate ramp) — same rationale as the zinc ramp. */
				'content-slate': 'rgb(var(--fp-content-slate) / <alpha-value>)',
				'content-slate-strong': 'rgb(var(--fp-content-slate-strong) / <alpha-value>)',
				'content-slate-secondary': 'rgb(var(--fp-content-slate-secondary) / <alpha-value>)',
				'content-slate-tertiary': 'rgb(var(--fp-content-slate-tertiary) / <alpha-value>)',
				'content-slate-muted': 'rgb(var(--fp-content-slate-muted) / <alpha-value>)',
				'content-slate-subtle': 'rgb(var(--fp-content-slate-subtle) / <alpha-value>)',
				'content-slate-disabled': 'rgb(var(--fp-content-slate-disabled) / <alpha-value>)',

				/* Lines — borders, dividers, rings. Hairlines, not surfaces. */
				line: 'rgb(var(--fp-line) / <alpha-value>)',
				'line-subtle': 'rgb(var(--fp-line-subtle) / <alpha-value>)',
				'line-strong': 'rgb(var(--fp-line-strong) / <alpha-value>)',
				'line-bold': 'rgb(var(--fp-line-bold) / <alpha-value>)',
				'line-zinc': 'rgb(var(--fp-line-zinc) / <alpha-value>)',
				'line-zinc-subtle': 'rgb(var(--fp-line-zinc-subtle) / <alpha-value>)',
				'line-zinc-strong': 'rgb(var(--fp-line-zinc-strong) / <alpha-value>)',
				'line-slate': 'rgb(var(--fp-line-slate) / <alpha-value>)',
				'line-slate-subtle': 'rgb(var(--fp-line-slate-subtle) / <alpha-value>)',
				'line-slate-strong': 'rgb(var(--fp-line-slate-strong) / <alpha-value>)',
				'line-inverse': 'rgb(var(--fp-line-inverse) / <alpha-value>)',

				/* Status — info (blue). Solids brighten; tinted backgrounds invert to dark tints. */
				info: 'rgb(var(--fp-info) / <alpha-value>)',
				'info-bright': 'rgb(var(--fp-info-bright) / <alpha-value>)',
				'info-strong': 'rgb(var(--fp-info-strong) / <alpha-value>)',
				'info-deep': 'rgb(var(--fp-info-deep) / <alpha-value>)',
				'info-deepest': 'rgb(var(--fp-info-deepest) / <alpha-value>)',
				'info-muted': 'rgb(var(--fp-info-muted) / <alpha-value>)',
				'info-muted-strong': 'rgb(var(--fp-info-muted-strong) / <alpha-value>)',
				'info-line': 'rgb(var(--fp-info-line) / <alpha-value>)',

				/* Status — danger (red). */
				danger: 'rgb(var(--fp-danger) / <alpha-value>)',
				'danger-bright': 'rgb(var(--fp-danger-bright) / <alpha-value>)',
				'danger-soft': 'rgb(var(--fp-danger-soft) / <alpha-value>)',
				'danger-strong': 'rgb(var(--fp-danger-strong) / <alpha-value>)',
				'danger-deep': 'rgb(var(--fp-danger-deep) / <alpha-value>)',
				'danger-muted': 'rgb(var(--fp-danger-muted) / <alpha-value>)',
				'danger-line': 'rgb(var(--fp-danger-line) / <alpha-value>)',

				/* Status — warning (amber) plus the orange/yellow one-offs. */
				warning: 'rgb(var(--fp-warning) / <alpha-value>)',
				'warning-bright': 'rgb(var(--fp-warning-bright) / <alpha-value>)',
				'warning-soft': 'rgb(var(--fp-warning-soft) / <alpha-value>)',
				'warning-strong': 'rgb(var(--fp-warning-strong) / <alpha-value>)',
				'warning-deep': 'rgb(var(--fp-warning-deep) / <alpha-value>)',
				'warning-muted': 'rgb(var(--fp-warning-muted) / <alpha-value>)',
				'warning-muted-strong': 'rgb(var(--fp-warning-muted-strong) / <alpha-value>)',
				'warning-line': 'rgb(var(--fp-warning-line) / <alpha-value>)',
				'warning-line-strong': 'rgb(var(--fp-warning-line-strong) / <alpha-value>)',
				'warning-deepest': 'rgb(var(--fp-warning-deepest) / <alpha-value>)',
				'accent-orange': 'rgb(var(--fp-accent-orange) / <alpha-value>)',
				'accent-orange-muted': 'rgb(var(--fp-accent-orange-muted) / <alpha-value>)',
				'accent-orange-bg': 'rgb(var(--fp-accent-orange-bg) / <alpha-value>)',
				'accent-yellow': 'rgb(var(--fp-accent-yellow) / <alpha-value>)',
				'accent-yellow-mid': 'rgb(var(--fp-accent-yellow-mid) / <alpha-value>)',
				'accent-yellow-bg': 'rgb(var(--fp-accent-yellow-bg) / <alpha-value>)',
				'accent-yellow-line': 'rgb(var(--fp-accent-yellow-line) / <alpha-value>)',
				'accent-yellow-strong': 'rgb(var(--fp-accent-yellow-strong) / <alpha-value>)',
				'accent-yellow-deep': 'rgb(var(--fp-accent-yellow-deep) / <alpha-value>)',

				/* Status — success (green / emerald). */
				success: 'rgb(var(--fp-success) / <alpha-value>)',
				'success-bright': 'rgb(var(--fp-success-bright) / <alpha-value>)',
				'success-soft': 'rgb(var(--fp-success-soft) / <alpha-value>)',
				'success-strong': 'rgb(var(--fp-success-strong) / <alpha-value>)',
				'success-deep': 'rgb(var(--fp-success-deep) / <alpha-value>)',
				'success-deepest': 'rgb(var(--fp-success-deepest) / <alpha-value>)',
				'success-line-subtle': 'rgb(var(--fp-success-line-subtle) / <alpha-value>)',
				'success-muted': 'rgb(var(--fp-success-muted) / <alpha-value>)',
				'success-line': 'rgb(var(--fp-success-line) / <alpha-value>)',
				'accent-emerald': 'rgb(var(--fp-accent-emerald) / <alpha-value>)',
				'accent-emerald-strong': 'rgb(var(--fp-accent-emerald-strong) / <alpha-value>)',
				'accent-emerald-soft': 'rgb(var(--fp-accent-emerald-soft) / <alpha-value>)',
				'accent-emerald-deep': 'rgb(var(--fp-accent-emerald-deep) / <alpha-value>)',
				'accent-emerald-muted': 'rgb(var(--fp-accent-emerald-muted) / <alpha-value>)',
				'accent-emerald-line': 'rgb(var(--fp-accent-emerald-line) / <alpha-value>)',
				'accent-emerald-bg': 'rgb(var(--fp-accent-emerald-bg) / <alpha-value>)',
				'accent-teal': 'rgb(var(--fp-accent-teal) / <alpha-value>)',
				'accent-teal-deep': 'rgb(var(--fp-accent-teal-deep) / <alpha-value>)',

				/* Accents — indigo / purple / sky / violet. */
				'accent-indigo': 'rgb(var(--fp-accent-indigo) / <alpha-value>)',
				'accent-indigo-strong': 'rgb(var(--fp-accent-indigo-strong) / <alpha-value>)',
				'accent-indigo-muted': 'rgb(var(--fp-accent-indigo-muted) / <alpha-value>)',
				'accent-indigo-line': 'rgb(var(--fp-accent-indigo-line) / <alpha-value>)',
				'accent-rose': 'rgb(var(--fp-accent-rose) / <alpha-value>)',
				'accent-rose-line': 'rgb(var(--fp-accent-rose-line) / <alpha-value>)',
				'accent-rose-muted': 'rgb(var(--fp-accent-rose-muted) / <alpha-value>)',
				'accent-purple': 'rgb(var(--fp-accent-purple) / <alpha-value>)',
				'accent-purple-muted': 'rgb(var(--fp-accent-purple-muted) / <alpha-value>)',
				'accent-purple-line': 'rgb(var(--fp-accent-purple-line) / <alpha-value>)',
				'accent-purple-deep': 'rgb(var(--fp-accent-purple-deep) / <alpha-value>)',
				'accent-sky': 'rgb(var(--fp-accent-sky) / <alpha-value>)',
				'accent-sky-bright': 'rgb(var(--fp-accent-sky-bright) / <alpha-value>)',
				'accent-violet': 'rgb(var(--fp-accent-violet) / <alpha-value>)',

				/* App shell — sidebar chrome and nav states. Light values are the exact hexes the shell already used. */
				'surface-sidebar': 'rgb(var(--fp-surface-sidebar) / <alpha-value>)',
				'surface-bold': 'rgb(var(--fp-surface-bold) / <alpha-value>)',
				'surface-selected': 'rgb(var(--fp-surface-selected) / <alpha-value>)',
				'surface-selected-alt': 'rgb(var(--fp-surface-selected-alt) / <alpha-value>)',
				'line-faint': 'rgb(var(--fp-line-faint) / <alpha-value>)',
				'content-slate-deep': 'rgb(var(--fp-content-slate-deep) / <alpha-value>)',
				'brand-navy': 'rgb(var(--fp-brand-navy) / <alpha-value>)',
				'brand-fill': 'rgb(var(--fp-brand-fill) / <alpha-value>)',
				'content-on-brand': 'rgb(var(--fp-content-on-brand) / <alpha-value>)',
				'surface-notch': 'rgb(var(--fp-surface-notch) / <alpha-value>)',
				'accent-yellow-muted': 'rgb(var(--fp-accent-yellow-muted) / <alpha-value>)',
				'surface-avatar': 'rgb(var(--fp-surface-avatar) / <alpha-value>)',

				/* Status chips + toasts. Applied through inline style, so these are consumed as rgb(var(--fp-x)). */
				'chip-success-bg': 'rgb(var(--fp-chip-success-bg) / <alpha-value>)',
				'chip-success-text': 'rgb(var(--fp-chip-success-text) / <alpha-value>)',
				'chip-success-line': 'rgb(var(--fp-chip-success-line) / <alpha-value>)',
				'chip-neutral-bg': 'rgb(var(--fp-chip-neutral-bg) / <alpha-value>)',
				'chip-neutral-text': 'rgb(var(--fp-chip-neutral-text) / <alpha-value>)',
				'chip-danger-bg': 'rgb(var(--fp-chip-danger-bg) / <alpha-value>)',
				'chip-info-bg': 'rgb(var(--fp-chip-info-bg) / <alpha-value>)',
				'chip-info-text': 'rgb(var(--fp-chip-info-text) / <alpha-value>)',
				'chip-warning-bg': 'rgb(var(--fp-chip-warning-bg) / <alpha-value>)',
				'chip-warning-text': 'rgb(var(--fp-chip-warning-text) / <alpha-value>)',
				'toast-success': 'rgb(var(--fp-toast-success) / <alpha-value>)',
				'toast-danger': 'rgb(var(--fp-toast-danger) / <alpha-value>)',
				'line-zinc-bold': 'rgb(var(--fp-line-zinc-bold) / <alpha-value>)',
				'line-zinc-tertiary': 'rgb(var(--fp-line-zinc-tertiary) / <alpha-value>)',
				'surface-slate-subtle': 'rgb(var(--fp-surface-slate-subtle) / <alpha-value>)',
				'stepper-active': 'rgb(var(--fp-stepper-active) / <alpha-value>)',
				'stepper-idle': 'rgb(var(--fp-stepper-idle) / <alpha-value>)',
				'stepper-line': 'rgb(var(--fp-stepper-line) / <alpha-value>)',

				/* Environment badge — sandbox/production pill in the sidebar. Gradient stops are applied via inline style. */
				'env-dev-bg': 'rgb(var(--fp-env-dev-bg) / <alpha-value>)',
				'env-dev-bg-mid': 'rgb(var(--fp-env-dev-bg-mid) / <alpha-value>)',
				'env-prod-bg': 'rgb(var(--fp-env-prod-bg) / <alpha-value>)',
				'env-prod-bg-mid': 'rgb(var(--fp-env-prod-bg-mid) / <alpha-value>)',
				'env-prod-line': 'rgb(var(--fp-env-prod-line) / <alpha-value>)',
				'env-prod-text': 'rgb(var(--fp-env-prod-text) / <alpha-value>)',

				/* Auth / banner surfaces — inline gradients and avatar tiles that must invert with their text. */
				'banner-bg': 'rgb(var(--fp-banner-bg) / <alpha-value>)',
				'banner-bg-mid': 'rgb(var(--fp-banner-bg-mid) / <alpha-value>)',
				'surface-avatar-navy': 'rgb(var(--fp-surface-avatar-navy) / <alpha-value>)',

				/* Restricted-environment banner — full-width inline gradients that must move with their text. */
				'banner-info-line': 'rgb(var(--fp-banner-info-line) / <alpha-value>)',
				'banner-info-text': 'rgb(var(--fp-banner-info-text) / <alpha-value>)',
				'banner-danger-bg': 'rgb(var(--fp-banner-danger-bg) / <alpha-value>)',
				'banner-danger-bg-mid': 'rgb(var(--fp-banner-danger-bg-mid) / <alpha-value>)',
				'banner-danger-line': 'rgb(var(--fp-banner-danger-line) / <alpha-value>)',
				'banner-danger-text': 'rgb(var(--fp-banner-danger-text) / <alpha-value>)',

				/* Charts — axis, grid and series colours applied through Recharts props and inline style. */
				'chart-axis': 'rgb(var(--fp-chart-axis) / <alpha-value>)',
				'chart-grid': 'rgb(var(--fp-chart-grid) / <alpha-value>)',
				'accent-indigo-bright': 'rgb(var(--fp-accent-indigo-bright) / <alpha-value>)',

				/* Off-palette values that predate the token layer — greys and accents written as arbitrary hex. */
				'surface-panel': 'rgb(var(--fp-surface-panel) / <alpha-value>)',
				'surface-panel-alt': 'rgb(var(--fp-surface-panel-alt) / <alpha-value>)',
				'surface-thumb': 'rgb(var(--fp-surface-thumb) / <alpha-value>)',
				'surface-thumb-alt': 'rgb(var(--fp-surface-thumb-alt) / <alpha-value>)',
				'surface-faint-inner': 'rgb(var(--fp-surface-faint-inner) / <alpha-value>)',
				'surface-thumb-inner': 'rgb(var(--fp-surface-thumb-inner) / <alpha-value>)',
				'surface-cool-strong': 'rgb(var(--fp-surface-cool-strong) / <alpha-value>)',
				'line-hairline': 'rgb(var(--fp-line-hairline) / <alpha-value>)',
				'line-muted': 'rgb(var(--fp-line-muted) / <alpha-value>)',
				'line-slate-deep': 'rgb(var(--fp-line-slate-deep) / <alpha-value>)',
				'content-grey': 'rgb(var(--fp-content-grey) / <alpha-value>)',
				'accent-teal-brand': 'rgb(var(--fp-accent-teal-brand) / <alpha-value>)',
				'accent-yellow-brand': 'rgb(var(--fp-accent-yellow-brand) / <alpha-value>)',
				'accent-indigo-soft': 'rgb(var(--fp-accent-indigo-soft) / <alpha-value>)',
				'accent-amber-soft': 'rgb(var(--fp-accent-amber-soft) / <alpha-value>)',
				'accent-blue-deep': 'rgb(var(--fp-accent-blue-deep) / <alpha-value>)',
				'accent-amber-mid': 'rgb(var(--fp-accent-amber-mid) / <alpha-value>)',

				/* Subscription-type chips — teal / violet / indigo triples applied through Chip props. */
				'chip-teal-bg': 'rgb(var(--fp-chip-teal-bg) / <alpha-value>)',
				'chip-teal-text': 'rgb(var(--fp-chip-teal-text) / <alpha-value>)',
				'chip-teal-line': 'rgb(var(--fp-chip-teal-line) / <alpha-value>)',
				'chip-violet-bg': 'rgb(var(--fp-chip-violet-bg) / <alpha-value>)',
				'chip-violet-text': 'rgb(var(--fp-chip-violet-text) / <alpha-value>)',
				'chip-violet-line': 'rgb(var(--fp-chip-violet-line) / <alpha-value>)',
				'chip-indigo-bg': 'rgb(var(--fp-chip-indigo-bg) / <alpha-value>)',
				'chip-indigo-text': 'rgb(var(--fp-chip-indigo-text) / <alpha-value>)',
				'chip-indigo-line': 'rgb(var(--fp-chip-indigo-line) / <alpha-value>)',
				'chip-type-static-bg': 'rgb(var(--fp-chip-type-static-bg) / <alpha-value>)',
				'chip-type-static-text': 'rgb(var(--fp-chip-type-static-text) / <alpha-value>)',
				'chip-type-metered-bg': 'rgb(var(--fp-chip-type-metered-bg) / <alpha-value>)',
				'chip-type-metered-text': 'rgb(var(--fp-chip-type-metered-text) / <alpha-value>)',
				'chip-type-boolean-bg': 'rgb(var(--fp-chip-type-boolean-bg) / <alpha-value>)',
				'chip-type-boolean-text': 'rgb(var(--fp-chip-type-boolean-text) / <alpha-value>)',
				'chip-type-config-bg': 'rgb(var(--fp-chip-type-config-bg) / <alpha-value>)',
				'chip-type-config-text': 'rgb(var(--fp-chip-type-config-text) / <alpha-value>)',
				'chip-type-default-bg': 'rgb(var(--fp-chip-type-default-bg) / <alpha-value>)',
				'chip-type-default-text': 'rgb(var(--fp-chip-type-default-text) / <alpha-value>)',

				/* Brand blue — pre-existing literals from tailwind.config.js, now themable. Light unchanged. */
				'brand-blue': 'rgb(var(--fp-brand-blue) / <alpha-value>)',
				'brand-blue-light': 'rgb(var(--fp-brand-blue-light) / <alpha-value>)',
				/* fp-tokens:end */

				sidebar: {
					DEFAULT: 'hsl(var(--sidebar-background))',
					foreground: 'hsl(var(--sidebar-foreground))',
					primary: 'hsl(var(--sidebar-primary))',
					'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
					accent: 'hsl(var(--sidebar-accent))',
					'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
					border: 'hsl(var(--sidebar-border))',
					ring: 'hsl(var(--sidebar-ring))',
					'text-accent-foreground': '#18181B',
				},
			},
			keyframes: {
				'accordion-down': {
					from: {
						height: '0',
					},
					to: {
						height: 'var(--radix-accordion-content-height)',
					},
				},
				'accordion-up': {
					from: {
						height: 'var(--radix-accordion-content-height)',
					},
					to: {
						height: '0',
					},
				},
				'spin-once': {
					'0%': { transform: 'rotate(0deg)' },
					'100%': { transform: 'rotate(360deg)' },
				},
				'command-palette-in': {
					from: { opacity: '0', transform: 'translateX(-50%) scale(0.92)' },
					to: { opacity: '1', transform: 'translateX(-50%) scale(1)' },
				},
				'command-palette-out': {
					from: { opacity: '1', transform: 'translateX(-50%) scale(1)' },
					to: { opacity: '0', transform: 'translateX(-50%) scale(0.92)' },
				},
			},
			animation: {
				'accordion-down': 'accordion-down 0.2s ease-out',
				'accordion-up': 'accordion-up 0.2s ease-out',
				'spin-once': 'spin-once 0.6s ease-in-out',
				'command-palette-in': 'command-palette-in 0.22s ease-in both',
				'command-palette-out': 'command-palette-out 0.18s ease-in both',
			},
		},
	},
	plugins: [animatePlugin],
};
